In [3]:
!pip install numpy

   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
   -- ------------------------------------- 0.8/12.9 MB 7.4 MB/s eta 0:00:02
   ------- -------------------------------- 2.4/12.9 MB 6.9 MB/s eta 0:00:02
   ------------ --------------------------- 4.2/12.9 MB 7.7 MB/s eta 0:00:02
   ------------------ --------------------- 6.0/12.9 MB 8.0 MB/s eta 0:00:01
   ------------------------ --------------- 7.9/12.9 MB 8.0 MB/s eta 0:00:01
   ----------------------------- ---------- 9.4/12.9 MB 8.0 MB/s eta 0:00:01
   ---------------------------------- ----- 11.0/12.9 MB 7.9 MB/s eta 0:00:01
   ---------------------------------------  12.8/12.9 MB 8.1 MB/s eta 0:00:01
   ---------------------------------------- 12.9/12.9 MB 7.9 MB/s  0:00:01


In [4]:
import numpy as np

In [6]:
arry = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [7]:
arry

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [9]:
arry_1 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [10]:
arry_1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [12]:
np.ones((1,3))

array([[1., 1., 1.]])

In [13]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [14]:
np.full((3,4), 6)

array([[6, 6, 6, 6],
       [6, 6, 6, 6],
       [6, 6, 6, 6]])

In [15]:
np.full((4,5), 3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [16]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
identity = np.eye(4)

In [19]:
identity

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
full = np.full((2,3),4)

In [21]:
full

array([[4, 4, 4],
       [4, 4, 4]])

In [23]:
arrange = np.arange(1,20,2)

In [24]:
arrange

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [25]:
np.arange(1,1000)

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

In [26]:
np.arange(1,1000, 99)

array([  1, 100, 199, 298, 397, 496, 595, 694, 793, 892, 991])

In [29]:
linespace = np.linspace(0,10 ,5)

In [30]:
linespace

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [32]:
size = arry_1.size

In [33]:
size

9

In [34]:
arry_1.ndim

2

In [39]:
arry_1.shape

(3, 3)

In [40]:
arry_1.dtype

dtype('int64')

In [42]:
arry_2= np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]], dtype='float32')

In [43]:
arry_2.dtype

dtype('float32')

In [44]:
arry_2.shape

(3, 4)

In [45]:
reshape_arry_2 = arry_2.reshape((4,3))

In [46]:
reshape_arry_2

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.],
       [ 7.,  8.,  9.],
       [10., 11., 12.]], dtype=float32)

In [49]:
change_type= reshape_arry_2.astype('int32')

In [50]:
change_type

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]], dtype=int32)

In [54]:
reshape= change_type.reshape((3,4))

In [55]:
reshape

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]], dtype=int32)

In [56]:
reshape.flatten()

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12], dtype=int32)