In [1]:
# import numpy

In [2]:
import numpy as np

In [3]:
arr = np.array((2,5))

In [4]:
arr

array([2, 5])

In [5]:
arr2 = np.array([[10,20,30,40,50],[70,100, 120,150 ,200]])

In [6]:
arr2

array([[ 10,  20,  30,  40,  50],
       [ 70, 100, 120, 150, 200]])

In [7]:
flat = arr2.flatten()


In [8]:
flat

array([ 10,  20,  30,  40,  50,  70, 100, 120, 150, 200])

In [9]:
flat[0]

np.int64(10)

In [10]:
flat[:3]

array([10, 20, 30])

In [11]:
flat[3:]

array([ 40,  50,  70, 100, 120, 150, 200])

In [12]:
flat[0:3]

array([10, 20, 30])

In [13]:
flat[-1]

np.int64(200)

In [14]:
idx = [0,2,4]

In [15]:
flat[idx]

array([10, 30, 50])

In [18]:
mask = flat > 50

In [19]:
flat[mask]

array([ 70, 100, 120, 150, 200])