In [2]:
#Create a 3x3 array filled with random number & print it's Shape

In [3]:
import numpy as np

In [4]:
random_arr = np.array([[100,200,300],[155,255,355],[999,9999,99999]])

In [5]:
random_arr

array([[  100,   200,   300],
       [  155,   255,   355],
       [  999,  9999, 99999]])

In [6]:
float_arr = np.array([1.1,2.2,3.3,4.4])

In [7]:
float_arr.dtype

dtype('float64')

In [8]:
#Convert an array of floats [1.1,2.2,3.3] into integers 

In [9]:
int_arr = float_arr.astype('int32')

In [10]:
int_arr

array([1, 2, 3, 4], dtype=int32)

In [11]:
#Use fancy indexing to extract even numbers from [1,2,3,4,5,6]

In [12]:
idx = [1,3,5]

In [13]:
fancy_arr = np.array([1,2,3,4,5,6])

In [14]:
fancy_arr[idx]

array([2, 4, 6])

In [15]:
#Reshape a 1D array of size 9 into a 3x3 Matrix

In [16]:
onedimension_arr = np.array([1,2,3,4,5,6,7,8,9])

In [18]:
matrix = onedimension_arr.reshape((3,3))

In [21]:
matrix.shape

(3, 3)

In [22]:
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
#Use boolean Masking to filter numbers greater than 50 in an array

In [24]:
boolean_masking = np.array([[4,6,10],[20,50,65],[69,70,80]])

In [25]:
mask = boolean_masking > 50

In [26]:
print(boolean_masking[mask])

[65 69 70 80]
